// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/** Provides access to calculated artifacts. */
@interface IXNMuseArtifactPacket : NSObject
- (nonnull instancetype)initWithHeadbandOn:(BOOL)headbandOn
                                     blink:(BOOL)blink
                                 jawClench:(BOOL)jawClench;
+ (nonnull instancetype)museArtifactPacketWithHeadbandOn:(BOOL)headbandOn
                                                   blink:(BOOL)blink
                                               jawClench:(BOOL)jawClench;

/**
 * Flag which represents if the %Muse Headband is on a person's head.
 * Headband On detection is one of the first things muse elements
 * algorithm does. If this flag is false you will not see other artifact
 * or band power data.
 * \return \c true if the headband is on. \c false otherwise.
 */
@property (nonatomic, readonly) BOOL headbandOn;

/**
 * Eye blinking flag.
 * \return \c true if an eye blink was detected. \c false otherwise.
 */
@property (nonatomic, readonly) BOOL blink;

/**
 * Jaw clench flag.
 * \return \c true if a jaw clench was detected. \c false otherwise.
 */
@property (nonatomic, readonly) BOOL jawClench;

@end
